/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/audit-logs': RouteRecordInfo<
      '/admin/audit-logs',
      '/admin/audit-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/billing': RouteRecordInfo<
      '/admin/billing',
      '/admin/billing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/inquiries': RouteRecordInfo<
      '/admin/inquiries',
      '/admin/inquiries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/pricing': RouteRecordInfo<
      '/admin/pricing',
      '/admin/pricing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/revenue': RouteRecordInfo<
      '/admin/revenue',
      '/admin/revenue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/callback': RouteRecordInfo<
      '/auth/callback',
      '/auth/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/code': RouteRecordInfo<
      '/code',
      '/code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact': RouteRecordInfo<
      '/contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/deliverables': RouteRecordInfo<
      '/deliverables',
      '/deliverables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design': RouteRecordInfo<
      '/design',
      '/design',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home': RouteRecordInfo<
      '/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invite/[token]': RouteRecordInfo<
      '/invite/[token]',
      '/invite/:token',
      { token: ParamValue<true> },
      { token: ParamValue<false> },
      | never
    >,
    '/legal/auto-billing': RouteRecordInfo<
      '/legal/auto-billing',
      '/legal/auto-billing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/privacy-policy': RouteRecordInfo<
      '/legal/privacy-policy',
      '/legal/privacy-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/refund-policy': RouteRecordInfo<
      '/legal/refund-policy',
      '/legal/refund-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/terms': RouteRecordInfo<
      '/legal/terms',
      '/legal/terms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/lint': RouteRecordInfo<
      '/lint',
      '/lint',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plan': RouteRecordInfo<
      '/plan',
      '/plan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pricing': RouteRecordInfo<
      '/pricing',
      '/pricing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile': RouteRecordInfo<
      '/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/team': RouteRecordInfo<
      '/team',
      '/team',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/audit-logs.vue': {
      routes:
        | '/admin/audit-logs'
      views:
        | never
    }
    'src/pages/admin/billing.vue': {
      routes:
        | '/admin/billing'
      views:
        | never
    }
    'src/pages/admin/inquiries.vue': {
      routes:
        | '/admin/inquiries'
      views:
        | never
    }
    'src/pages/admin/pricing.vue': {
      routes:
        | '/admin/pricing'
      views:
        | never
    }
    'src/pages/admin/revenue.vue': {
      routes:
        | '/admin/revenue'
      views:
        | never
    }
    'src/pages/auth/callback.vue': {
      routes:
        | '/auth/callback'
      views:
        | never
    }
    'src/pages/code.vue': {
      routes:
        | '/code'
      views:
        | never
    }
    'src/pages/contact.vue': {
      routes:
        | '/contact'
      views:
        | never
    }
    'src/pages/deliverables.vue': {
      routes:
        | '/deliverables'
      views:
        | never
    }
    'src/pages/design.vue': {
      routes:
        | '/design'
      views:
        | never
    }
    'src/pages/home.vue': {
      routes:
        | '/home'
      views:
        | never
    }
    'src/pages/invite/[token].vue': {
      routes:
        | '/invite/[token]'
      views:
        | never
    }
    'src/pages/legal/auto-billing.vue': {
      routes:
        | '/legal/auto-billing'
      views:
        | never
    }
    'src/pages/legal/privacy-policy.vue': {
      routes:
        | '/legal/privacy-policy'
      views:
        | never
    }
    'src/pages/legal/refund-policy.vue': {
      routes:
        | '/legal/refund-policy'
      views:
        | never
    }
    'src/pages/legal/terms.vue': {
      routes:
        | '/legal/terms'
      views:
        | never
    }
    'src/pages/lint.vue': {
      routes:
        | '/lint'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/plan.vue': {
      routes:
        | '/plan'
      views:
        | never
    }
    'src/pages/pricing.vue': {
      routes:
        | '/pricing'
      views:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | '/profile'
      views:
        | never
    }
    'src/pages/team.vue': {
      routes:
        | '/team'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
